trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: false
endOfLine: lf
singleAttributePerLine: true
plugins:
  - prettier-plugin-organize-imports
  - prettier-plugin-sh
  - prettier-plugin-tailwindcss
