version: "3.8"
services:
  devcontainer:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/workspaces/dansdata/landing_page:cached
    command: sleep infinity
